[package]
name = "buildings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
world_generation = {path = "../../engine/world_generation"}

[features]
tracing = []
