[package]
name = "asset_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.204"
serde_json = "1.0.120"
bevy = "0.14.2"
ron = "0.8.1"
